# Generated by Django 4.0.3 on 2022-04-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_eventdate_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='type',
        ),
    ]
